services:
  db:
    image: postgres:15
    container_name: nest_postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root123
      POSTGRES_DB: testnest
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      # Usa o usuário nativo do sistema para um ping de conexão rápido e seguro
      test: ["CMD-SHELL", "pg_isready -h localhost -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 15s

  rabbitmq:
    image: rabbitmq:3-management
    container_name: nest_rabbitmq
    restart: always
    ports:
      - "5672:5672"   # Porta de comunicação da fila
      - "15672:15672" # Porta do painel web
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      # Comando oficial e leve para validar se a aplicação responde a pings
      test: ["CMD-SHELL", "rabbitmq-diagnostics -q ping"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 15s

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest_api
    restart: always
    ports:
      - "3000:3000"
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: root
      DATABASE_PASSWORD: root123
      DATABASE_NAME: testnest
      DATABASE_URL: "postgresql://root:root123@db:5432/testnest?schema=public"
      RABBITMQ_URL: "amqp://guest:guest@rabbitmq:5672"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    # Executa os comandos do Prisma em sequência e inicia a aplicação
    command: sh -c "npx prisma db push && npx prisma generate && npm run start:dev"
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

volumes:
  pgdata:
